{% set name = "pgeocode" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pgeocode-{{ version }}.tar.gz
  sha256: 37d6caf74e9f2b1e69762811953df5b43fe7f1806833c83bf85a60dd784dff9e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - numpy
    - pandas
    - python >=3.8
    - requests

test:
  imports:
    - pgeocode
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pgeocode/
  summary: Approximate geocoding
  license: BSD-1-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
